### ISSUE TITLE
Intellisense / tab completion not working for PySide2.QtCore.Qt.*

### ISSUE THREAD

**Issue by LightCC** [seanwu1105/vscode-qt-for-python#10]
It appears the entire PySide2.QtCore.Qt.* set of symbols is not supported by Intellisense.

Not sure if this is a Qt for Python issue or something else.

For example, the window that pops up when attempting to use Intellisense on Qt.* just has mro and a bunch of double underscore symbols:
![image](https://user-images.githubusercontent.com/19731713/64483665-6a684100-d1d4-11e9-8ab3-db3ef9a890f7.png)

I suppose I could have something setup wrong as well - I'm fairly new to Python and new to Qt.

P.S. what is the best way to get help on PySide2 modules?  Is there some command-line option, or any other VS Code option beyond digging through doc.qt.io?

**Comment by LightCC** [comment]
Could this be a generic Intellisense problem for Python with nested packages, rather than specific to Qt for Python?

Working on a package/module tutorial with nested packages, I run into a similar problem. When I begin typing the top-level package for my `demo_reader` package, intellisense appears to list all nested packages in the list:
![image](https://user-images.githubusercontent.com/19731713/64494800-47cf3a00-d25f-11e9-9402-a805de4cfc56.png)

And when I complete the first `demo_reader` name, and hit `.` Intellisense pulls up again, but the list is definitely not only the packages/modules/symbols under demo_reader, it appears to be some weird mix of the top-level items. If I type compressed fully, it is showing compressed along with the top-level demo_reader (i.e. `demo_reader.compressed`):
![image](https://user-images.githubusercontent.com/19731713/64494841-ca57f980-d25f-11e9-82a7-df6796e71811.png)

and if I hit tab, I get a double entry on demo_reader as a result:
![image](https://user-images.githubusercontent.com/19731713/64494850-e5c30480-d25f-11e9-99ac-d68795028d00.png)

Hitting `.` again pulls up the Intellisense window, but populates the list from the top-level again, rather than at the appropriate nested starting point.

**Comment by seanwu1105** [comment]
This extension does not provide any additional IntelliSense support. [This issue](https://github.com/davidhalter/jedi/issues/1287#issuecomment-468010954) shows that the tab completion does not work because PyQt5 and PySide2 are C extension for Python. [coc-python](https://github.com/neoclide/coc-python) and [PyQt5-stubs](https://github.com/stlehmann/PyQt5-stubs) might help but I have not tried. I am closing this issue as an upstream issue.
