### ISSUE TITLE
pyuic5 autocompile

### ISSUE THREAD

**Issue by kinekt2000** [seanwu1105/vscode-qt-for-python#100]
Is there a way to autocompile ui files with pyuic?

**Comment by seanwu1105** [comment]
Currently no. A pull request is welcome.

**Comment by DaveA50** [comment]
This is possible using a different vscode extension, [File Watcher](https://marketplace.visualstudio.com/items?itemName=appulate.filewatcher&ssr=false). 

Adding this config to your settings, changing:
```
    "filewatcher.commands": [
        {
            "match": "\\.ui",
            "isAsync": true,
            "cmd": "pyuic5 \"${file}\" -o \"${fileDirname}\\${fileBasenameNoExt}.py\"",
            "event": "onFolderChange"
        }
    ]
```

This also works for PyQt6, PySide2, PySide6, by changing the cmd to pyuic6, pyside2-uic, or pyside6-uic respectively. It works when an external program makes the files change (like QT Designer).

**Comment by seanwu1105** [comment]
Closing with 22045a0bb99d127c74d15e66846f4ac0a973b30f on v1.0.0.
