### ISSUE TITLE
[Suggestion] Add special color for translation context comments

### ISSUE THREAD

**Issue by daravi** [seanwu1105/vscode-qt-for-python#115]
I think it could be useful to highlight the translation context comments differently:
```
Text {
    id: txt1;
    // This user interface string is only used here
    //: The back of the object, not the front
    //~ Context Not related to back-stepping
    text: qsTr("Back");
}
```
Context in //~ Context could also be highlighted differently since it won't be copied to the TS file. This is definitely a nice to have and not at all necessary so feel free to close as "won't do".

**Comment by seanwu1105** [comment]
@daravi That is a great suggestion. I would follow [the official documentation](https://doc.qt.io/qt-5/i18n-source-translation.html#translator-comments) to implement the syntax highlighting if I have time.

**Comment by daravi** [comment]
@seanwu1105 Can `//:` be highlighted in the same way as `//=` and `//~`?

**Comment by seanwu1105** [comment]
@daravi Like this?

![Screenshot from 2021-05-21 23-41-20](https://user-images.githubusercontent.com/14951000/119163603-21cae700-ba8e-11eb-8777-1641ad093afc.png)

**Comment by daravi** [comment]
Yes I think that would be better! Thanks!
