### ISSUE TITLE
Missing script in packaged extenstion 1.1.2

### ISSUE THREAD

**Issue by Orblux** [seanwu1105/vscode-qt-for-python#125]
Hi,

Thanks for the great work! You probably already saw it but the python/scripts folder is not bundled with the package of the extension in version 1.1.2..
You can also see it with the failed action in Github Actions.

As workaround, one can just copy the folder form 1.1.1 version (after downgrade or pull it from git) and copy it in the extension folder.

Thanks again for the great work.

**Comment by seanwu1105** [comment]
@Orblux 

Thanks for the report! The root cause is https://github.com/microsoft/vscode-vsce/issues/576. I will downgrade `vsce` and release again.
