### ISSUE TITLE
Search active python interpreter path for Qt Designer

### ISSUE THREAD

**Issue by DaelonSuzuka** [seanwu1105/vscode-qt-for-python#13]
PySide2 on pip comes with a copy of Qt Designer(I don't know if PyQt5 is similar). It should be possible to check site-packages for `PySide2/designer.exe` and use that copy instead of having to manually set the path.

Additionally, if it's possible to check VSCode's active python interpreter path, then you could prioritize the selected python installation, even if it's a virtual environment. 

An option to control whether it will silently fall back to checking system paths if the active interpreter is missing a copy of Designer would also be useful, in case you have projects using different versions of PySide2.

**Comment by seanwu1105** [comment]
@DaelonSuzuka that's a great idea. I will take a look about the Qt Designer  from PySide. A pull request is always welcome.

**Comment by seanwu1105** [comment]
Closing with a929c1c590845bac3577e3b0228b67a3a85a01c1 on v1.0.0.
