### ISSUE TITLE
color widgets like in CSS?

### ISSUE THREAD

**Issue by ewerybody** [seanwu1105/vscode-qt-for-python#137]
You know when editing CSS for the web one has these little correctly colored cubes next to a color value.
When hovering one even gets a popup to change the color in place:
![image](https://user-images.githubusercontent.com/218956/126467938-0d6ab852-b3f4-4414-a2a0-bea90c269ad8.png)

So that must be a VS Code built-in feature. Could we have this on `.qss` as well?

I'd look into it myself but I still dunno where to start :/

**Comment by naveeng2402** [comment]
Yes, this one is a must want feature to make working with qss a lot easier;
Also it'll be great to have autocompletion in qss

**Comment by seanwu1105** [comment]
A language server for QSS is required to fulfill this request. The only reference for the QSS syntax could only be found [here](https://doc.qt.io/qt-5/stylesheet-reference.html). However, I do not have enough time to implement the server according to the reference in the near future. A pull request would be greatly helpful.

**Comment by seanwu1105** [comment]
Wait for the official language server: https://bugreports.qt.io/browse/QTBUG-106009

**Comment by seanwu1105** [comment]
Implemented with `registerColorProvider` without the official language server. Thus, the behavior might diverge from the official language spec.
