### ISSUE TITLE
UI compiler can not be found in virtual environement

### ISSUE THREAD

**Issue by svenito92** [seanwu1105/vscode-qt-for-python#151]
Hello

I'd like to use the features of "Qt for Python" in my projects. I am working with virtual environments inside my project directory.
In these environments, PySide6 is installed. The Python extension for vscode recognizes my virtual environment without problem. I can correctly select the virtual interpreter (see attached image). However, when I create a random UI file and try to compile it, "Qt for Python" does not find the correct binary (pyside6-uic.exe) even though the pyside binaries can be found inside the virtual environment (see attached image).

The attached image serves as a sample to reconstruct the Problem:
1. Create empty folder and open in vscode
2. Create virtual environment with "venv". Choose .\.venv\ as folder
3.  Activcate virtual environment and install PySide6 with pip
4. Create or copy random .ui file inside Project (e.g. with pyside6-designer.exe)
5. In the context menu of the created file choose "Compile Form ..."

Is there an option to search for binaries under local directory subpaths? Or could there be an option to search for the binaries at the same location as the Python interpreter (which is correctly chosen from the virtual environment)?

![Working_Example](https://user-images.githubusercontent.com/61381861/133421258-276dfa3f-be43-4f29-8ffa-fb86190aa95a.png)

**Comment by seanwu1105** [comment]
@svenito92 Sorry for the late. I have pushed [a fix](https://github.com/seanwu1105/vscode-qt-for-python/pull/168) for this problem. Could you help me to verify it?

**Comment by svenito92** [comment]
@seanwu1105 Thanks for addressing the problem. I tried my best to validate your approach. However I have to admit it has been the first time I tried to build a VS Code Extension by myself... so this was now territory for me 😉

All I can say is: It worked like a charm 👍.

I have only one addition to the way you handle the case of not getting a _pythonExecCommand_. Currently you just return _'python'_. Which then can either work (but outside of the environment depending on global packages and oblivious for the user) or it will trigger the default error message of not finding the correct executables.
I would suggest to throw a distinct error message saying something like _"Interpreter path could not be obtained by the Python extension."_ This would hint the user that the problem lies in the communication between your extension and the **ms-python** extension.
As return value, you could use the value from the **python.defaultInterpreterPath** setting (It's also 'python' by default). This seems to be the new setting to replace the deprecated **python.pythonPath** setting.

**Comment by seanwu1105** [comment]
@svenito92 Thanks for the suggestion! I have implemented and tested it. This fix will be released soon.
