### ISSUE TITLE
Doubt about configuration

### ISSUE THREAD

**Issue by betopicapiedra** [seanwu1105/vscode-qt-for-python#152]
_**I do not know what goes in each of these parameters, I would like to see a clear example of how to do it**_

![2021-09-21_18h55_04](https://user-images.githubusercontent.com/5233084/134262908-1b22229b-31fd-45b7-ace2-f4b686f7a725.png)

![2021-09-21_18h57_08](https://user-images.githubusercontent.com/5233084/134262938-45ba121c-13a5-413c-895b-241090a00072.png)

**Comment by seanwu1105** [comment]
I am not sure what you need for clarification. The examples have been added to the description for each preference. Please provide more details about your question, such as your guess, trial and possible error messages or unexpected behavior.

**Comment by seanwu1105** [comment]
Close due to inactivity.
