### ISSUE TITLE
ExecutionError: Command failed: "pyuic5"

### ISSUE THREAD

**Issue by baudzhou** [seanwu1105/vscode-qt-for-python#153]
When compiling .ui file into .py, I got such error:

> ExecutionError: Command failed: "pyuic5" -o "d:\pose\physical_test\.qt_for_python\uic\physical_test_client.py" "d:\pose\physical_test\physical_test_client.ui" **'"pyuic5"'** �����ڲ����ⲿ���Ҳ���ǿ����еĳ��� ���������ļ���

There is an extra **"pyuic5"** arg added to the complie command.
I tried pyuic5 -o "d:\pose\physical_test\.qt_for_python\uic\physical_test_client.py" "d:\pose\physical_test\physical_test_client.ui" command, and it worked.

**Comment by seanwu1105** [comment]
It seems to be a bug after some extension interface update from Visual Studio Code and maybe its Python extension. I will take a look if I can find a time. Still, thank you for the reporting!

**Comment by baudzhou** [comment]
> It seems to be a bug after some extension interface update from Visual Studio Code and maybe its Python extension. I will take a look if I have a time. Still, thank you for the reporting!

I tried another extension "PYQT Integration" .  It also works like this one. 
I tried to disable all of my extensions, but it still could not work.

**Comment by braindust** [comment]
manually setting the path to \Scripts\pyuic6.exe in the venv path works for me.
Maybe this helps.

**Comment by seanwu1105** [comment]
We should leverage [the public APIs](https://github.com/microsoft/vscode-python/blob/main/src/client/api.ts) provided from the official Python extension for more robust binding.

**Comment by seanwu1105** [comment]
@baudzhou Sorry for the late. I have pushed [a fix](https://github.com/seanwu1105/vscode-qt-for-python/pull/168) for this problem. Could you help me to verify it?
