### ISSUE TITLE
Compiling .qrc with rcc

### ISSUE THREAD

**Issue by RESP3CT88** [seanwu1105/vscode-qt-for-python#175]
I can't figure out what I'm doing wrong. The extension is not compiling my qrc file. I don't know where to find any error information, there are no notifications about anything going wrong.

In my settings.json I have:
```
{
    "qtForPython.rcc.path": "pyside2-rcc"
}
```

pyside2-rcc is a path variable and accessible from everywhere. I am using Ubuntu 20.04.

**Comment by seanwu1105** [comment]
@RESP3CT88 Currently, we do not support environment variable in tool executable. We only resolve environment variable in command arguments. This feature can be added in next release.

**Comment by RESP3CT88** [comment]
Even when I right click on my .qrc file and click "Compile Resource File into Qt for Python File" nothing happens.

And I modified my settings.json to:

{
    "qtForPython.rcc.path": "/usr/local/bin/pyside2-rcc"
}

**Comment by seanwu1105** [comment]
@RESP3CT88 If there is an error, there should be an error message box popping up. Do you get any message from it? If it is successfully executed, the compiled files should be generated in `./.qt_for_python/`.

**Comment by seanwu1105** [comment]
Close as unable to reproduce.
