### ISSUE TITLE
Support for Multi Root workspace for UI compiler output

### ISSUE THREAD

**Issue by ugur1yildiz** [seanwu1105/vscode-qt-for-python#191]
It will be appreciated to add option to create ui compiler output referencing to the root folder of ui file in multi root folder workspcae.
It is now referenced to the first folder. 

Here is the adaptation document.
[https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs](https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs)

**Comment by seanwu1105** [comment]
Close with 28163536ad193d49c0405d8bb632f57f03e954da.
