### ISSUE TITLE
Download extension in Python Virtual Environment (venv)

### ISSUE THREAD

**Issue by avgustos** [seanwu1105/vscode-qt-for-python#205]
Hi, I have downloaded PyQt6 in my venv. I have installed the extension in VS Code, do I also need to download it in my venv to work properly?

**Comment by seanwu1105** [comment]
No, I don't think so. The extension will use the Python interpreter you specified in the official Python extension to invoke the utility tools. Namely, if the Python interpreter has PyQt6 in its venv, it should work just fine.
