### ISSUE TITLE
升级到最新3.0都设置好了,竟然邮件都无法编辑ui文件了?右键生成新的ui.py也不行了!还不如老版本啊.

### ISSUE THREAD

**Issue by jiayouzl** [seanwu1105/vscode-qt-for-python#246]
升级到最新3.0都设置好了,竟然邮件都无法编辑ui文件了?右键生成新的ui.py也不行了!还不如老版本啊.

**Comment by jiayouzl** [comment]
"qtForPython.designer.path": "pyside6-designer",
    "qtForPython.qmllint.path": "pyside6-qmllint",
    "qtForPython.uic.path": "pyside6-uic",
    "qtForPython.rcc.path": "pyside6-rcc"

**Comment by jiayouzl** [comment]
设置没有问题,老版本就这样设置的,现在升级后右键编辑无反应,右键编译也没反应.

**Comment by jiayouzl** [comment]
请速修复下

**Comment by seanwu1105** [comment]
Hi @jiayouzl, please provide the error messages in the output channel.

**Comment by seanwu1105** [comment]
Should be fixed with 35ea0d90ef1885993fe7efc777f4e763e6f23944.
