### ISSUE TITLE
restore qmake support

### ISSUE THREAD

**Issue by gushuguo** [seanwu1105/vscode-qt-for-python#250]
from version 2.3.0, the qmake and pro file support has been dropped, but Qt5 is still very popular, is that possible to restore the feature? very thanks!!

**Comment by seanwu1105** [comment]
Close due to no response.

**Comment by gushuguo** [comment]
> Hi @gushuguo, I am wondering what is the use case of qmake and `pro` file in Qt for Python. For me, qmake is used only when you working on Qt with C++. It seems to be out-of-scope for this Visual Studio Code extension. Please let me know if there is anything wrong with my understanding.

Hi, sorry to reply now. you are right that I am working on Qt with C++, In my situation, vscode is my code editor, I also use it to edit 'pro' file of qmake, so the syntax highlighting is very important and useful， also the smart intelligence （if supported）。maybe my consideration is not very suitable, but there is no very good extension for Qt now,  just for your reference.

**Comment by seanwu1105** [comment]
Hi @gushuguo, thanks for the feedback. I think using C++ with Qt is out of the scope of this extension. I can definitely create another extension for such support but it needs more time to do so.
