### ISSUE TITLE
Error while loading shared libraries: libQt6QmlCompiler.so.6

### ISSUE THREAD

**Issue by Egenet** [seanwu1105/vscode-qt-for-python#253]
Error: /home/username/.local/lib/python3.8/site-packages/PySide6/qmllint: error while loading shared libraries: libQt6QmlCompiler.so.6: cannot open shared object file: No such file or directory
while executing '/home/username/.local/lib/python3.8/site-packages/PySide6/qmllint --json /home/username/development/python/pyside/application/qml/main.qml'

**What might be the reason, and how to fix on Linux Mint?**

**Comment by seanwu1105** [comment]
I believe this is caused by an upstream issue: https://bugreports.qt.io/browse/PYSIDE-2115

It should be good if you install PySide 6.3 or earlier. It seems the error occurs only on PySide 6.4.

**Comment by Egenet** [comment]
Rolled back to version 6.3 with:
**$ python -m pip uninstall pyside6
$ pip install -Iv PySide6==6.3**
And the error warning has disappeared.
Thank you!
