### ISSUE TITLE
`qmllint`在ctrl + s保存qml文件时会弹出内容为空白的error

### ISSUE THREAD

**Issue by linyang-bytedance** [seanwu1105/vscode-qt-for-python#254]
![image](https://user-images.githubusercontent.com/118248420/203484699-9222d0cc-0c11-4bd8-8e7d-14170fbaef25.png)

**Comment by linyang-bytedance** [comment]
应该是出现了Error，但message为空的情况？

**Comment by seanwu1105** [comment]
I cannot reproduce the error but it could be related to this one https://github.com/seanwu1105/vscode-qt-for-python/issues/253 since you are using PySide 6.4.0.1. Let me know if there's still an error after you downgrade to 6.3.0.

**Comment by linyang-bytedance** [comment]
> I cannot reproduce the error but it could be related to this one #253 since you are using PySide 6.4.0.1. Let me know if there's still an error after you downgrade to 6.3.0.

I tried downgrading PySide to 6.3.0 and everything works as usual!
