### ISSUE TITLE
Wrongly names compiled resource files

### ISSUE THREAD

**Issue by britesc** [seanwu1105/vscode-qt-for-python#262]
Type: <b>Bug</b>

1. Select QRC File from File List Panel
2. Right Click and Select Compile.
3. The file is compiled but named as rc_filename.py
4. It needs to be named filename_rc.py to enable it to be found within the associated  .ui file.
5. Unfortunately, manually renaming the file means it is over written on an update, or changing the filename in the .ui file means that is overwritten during an update.
Thank you for your help.

Extension version: 3.0.2
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 5.19.0-29-generic snap
Modes:
Sandboxed: No

**Comment by seanwu1105** [comment]
Hi @britesc,

Thanks for the report. Could you tell me more about the reason that it needs to be named `filename_rc.py` _to enable it to be found within the associated .ui file_?

Currently, the default naming for the compiled file is originated from the naming convention of `pyside6-project`. You can read more details with `pyside6-project --help`.

If you want to customize the output filename, you can always set the options with extension configuration: `qtForPython.rcc.options`.

**Comment by britesc** [comment]
Hi,
Really quick.
When using Designer or Creator it save a resource file as filename.qrc or
filename.ui
If I right click on either of these files I get the option through your
great tool to compile them.
filename.qrc is compiled to rc_filename.py and filename.ui to
ui_filename.py.
Yet within the ui_filename.py the reference to the rc file has been entered
as filename_rc

I hope this helps. It is just a great tool for beginners, especially.

Kind regards,

Julian

**Comment by seanwu1105** [comment]
Hi @britesc,

Is it possible to provide a minimal sample `.ui` file with a reference to an rc file for me to reproduce the problem? That would be really helpful.

**Comment by britesc** [comment]
Hi,
Yes I will try as soon as possible.
I will also give details of the OS, VSCode and PySide6 I am using.
Will be a little while whilst I rig something up. I'm fairly new to python etc, but have used other languages for over 4 centuries now. 😂😂😂😎
Regards,
Julian

**Comment by seanwu1105** [comment]
Close due to inactivity.
