### ISSUE TITLE
Add QML debugger feature

### ISSUE THREAD

**Issue by kelteseth** [seanwu1105/vscode-qt-for-python#271]
It would be nice to be able to debug qml code. For this there is the vscode https://code.visualstudio.com/api/extension-guides/debugger-extension. The Qt side is not so well documented sadliy. 

All of these debugging features are plugins (https://github.com/qt/qtdeclarative/tree/dev/src/plugins/qmltooling) get compiled into the executable when running "Profile" CMake mode in QtCreator.

We can see what the QtCreator adds as arguments when running a test app:
```
\test.exe "-qmljsdebugger=port:50124,block,services:DebugMessages,QmlDebugger,V8Debugger,QmlInspector,DebugTranslation" 
```

On the qml side we have two server
- LocalServer https://github.com/qt/qtdeclarative/blob/dev/src/plugins/qmltooling/qmldbg_local/qlocalclientconnection.cpp
- TCPServer https://github.com/qt/qtdeclarative/blob/dev/src/plugins/qmltooling/qmldbg_tcp/qtcpserverconnection.cpp

QtCreaor debugger plugin https://github.com/qt-creator/qt-creator/tree/master/src/plugins/debugger/qml 

For example,  [adding a breakpoint](https://github.com/qt-creator/qt-creator/blob/master/src/plugins/debugger/qml/qmlengine.cpp#L1378) is a simple Json that then gets [send to the application ](https://github.com/qt-creator/qt-creator/blob/master/src/plugins/debugger/qml/qmlengine.cpp#L1608)

**Comment by seanwu1105** [comment]
Thanks for the suggestion. However, the qmljsdebugger is not shipped with any Qt for Python library, including PySide6 and PyQt6. This makes the extension hard to support all native platforms out of the box. This extension aims to integrate tools provided by the library into Visual Studio Code editor. Namely, building the debugger plugin from source would be out of the scope of this extension. If the debugger is provided by the library in the future, this might be an viable enhancement.
