### ISSUE TITLE
设置好相关路径后使用插件无反应

### ISSUE THREAD

**Issue by Nexround** [seanwu1105/vscode-qt-for-python#275]
{
    "qtForPython.designer.path": "C:\\ProgramData\\Anaconda3\\envs\\py310\\Scripts\\pyside6-designer.exe",
    "qtForPython.uic.path": "C:\\ProgramData\\Anaconda3\\envs\\py310\\Scripts\\pyside6-uic.exe",
    "qtForPython.rcc.path": "C:\\ProgramData\\Anaconda3\\envs\\py310\\Scripts\\pyside6-rcc.exe"
}
路径如上面的配置，使用插件功能都没有反应，也没有报错信息
环境: anaconda, python3.10, vscode1.75.1

**Comment by seanwu1105** [comment]
It would be helpful to provide any logging messages from the "Qt for Python" output channel. Note that the error messages might be generated after you restart the editor.

**Comment by Nexround** [comment]
PySide6.4.2

[INFO  - 01:38:27] "qmlls is enabled with latest config: {\"command\":[\"C:\\\\ProgramData\\\\Anaconda3\\\\envs\\\\py310\\\\Scripts\\\\pyside6-qmlls.exe\"],\"options\":[]}"
[Warn  - 01:38:27] registration of file udates failed, will miss file changes done outside the editor due to error -32603 Request client/registerCapability failed with message: No feature implementation for workspace.didChangeWatchedFiles found. Registration failed.
尝试执行了插件功能，没有进一步的报错了

**Comment by XLjiangA** [comment]
笑死我执行之后生成的是cpp的代码

**Comment by XLjiangA** [comment]
我刚开始也遇到没反应了 之后就开始一直生成cpp的 找不到地方改 麻了

**Comment by XLjiangA** [comment]
我反复确认了好多遍我安装的是qt for python 哈哈哈

**Comment by XLjiangA** [comment]
我可以用了 把所有设置的路径删掉,别设置就好了 他会自动获取

**Comment by XLjiangA** [comment]
然后一运行 AttributeError: 'mainForm' object has no attribute 'setCentralWidget'. Did you mean: 'centralwidget'?
头大
