### ISSUE TITLE
No qmlls?

### ISSUE THREAD

**Issue by Usercyk** [seanwu1105/vscode-qt-for-python#279]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/109349977/220939107-57053c6b-4d48-44fe-a0ed-1d4671c00386.png">
我也不知道发生了什么……有段时间没用后就变成了这样？
pyqt5, python3.10.5, vscode1.75.1
这是因为没有Pyside6的原因，不需要管？还是真的哪里报错了啊？

**Comment by Usercyk** [comment]
之前有段时间没有写代码，但是插件好像更新了，突然这样

**Comment by seanwu1105** [comment]
qmlls requires PySide6 6.4 or later. You can disable it in the extension configuration.

**Comment by Usercyk** [comment]
thanks
