### ISSUE TITLE
插件报错 UnexpectedError: {} (caught: { "source": { "source": { "source": {} } } })

### ISSUE THREAD

**Issue by zhiyiYo** [seanwu1105/vscode-qt-for-python#286]
为啥每次启用 VSCode 时都会报这个错呀？

**Comment by seanwu1105** [comment]
Please provide your environment info, including the version of the Qt dependency and the extension logging. You can get the logging messages from Output > Qt for Python.

**Comment by zhiyiYo** [comment]
### environment
|environment|version|
|:-----:|:----:|
|OS|Windows11|
|VSCode|1.76.0|
|Python| 3.8.6|
|PyQt| 5.15.6|
|Qt| 5.15.2|




### log
```
[ERROR - 23:32:14] UnexpectedError: {}
(caught: {
  "source": {
    "source": {
      "source": {
        "source": {}
      }
    }
  }
})
[INFO  - 23:32:15] An observable is completed
[ERROR - 23:32:15] UnexpectedError: {}
(caught: {
  "source": {
    "source": {
      "source": {}
    }
  }
})
[INFO  - 23:32:15] An observable is completed
[INFO  - 23:32:15] qmlls has been stopped
```

**Comment by seanwu1105** [comment]
According to the log and your environment, it is possible that the extension tries to activated the `qmlls` but could not find it. Could you disable the `qtForPython.qmlls.enabled` in the configuration and see if the error message still exists?

**Comment by zhiyiYo** [comment]
禁用这个配置项之后还是报错诶

**Comment by zhiyiYo** [comment]
而且奇怪的是这里有两个复选框一直无法取消选中
![image](https://user-images.githubusercontent.com/65096819/222998719-bd42b5f1-9f20-4782-9203-80d3532fbc47.png)

**Comment by seanwu1105** [comment]
> 而且奇怪的是这里有两个复选框一直无法取消选中

The extension does not set the configuration programmatically, and thus I think the cause of the configuration "lock" is from another extension or something else.

Since I cannot reproduce the problem, I am wondering if you can provide a minimal PyQt project reproducing the issue for me to clarify and investigate it. Thank you for the report.

**Comment by seanwu1105** [comment]
Hi @zhiyiYo, I tried to reproduce the problem but the error messages are displayed correctly. 

![Screenshot from 2023-03-06 09-25-17](https://user-images.githubusercontent.com/14951000/223141167-083f4ac3-a8e6-4302-ab5c-84f89a9c8fe3.png)

Basically, the extension requires PySide6 or other Qt libraries to work. You can always disable the Qt tool auto registration by configuring the following in your workspace settings.

```json
{
    "qtForPython.qmlls.enabled": false,
    "qtForPython.rcc.liveExecution.enabled": false,
    "qtForPython.uic.liveExecution.enabled": false
}
```

Currently, there will be still one error message indicating the qrc file could not be parsed correctly. I fix that later.
