### ISSUE TITLE
RCC default options 

### ISSUE THREAD

**Issue by retconx** [seanwu1105/vscode-qt-for-python#289]
The Rcc default option should be
"${resourceDirname}${pathSeparator}${resourceBasenameNoExtension}\_rc.py"
instead of
"${resourceDirname}${pathSeparator}rc\_${resourceBasenameNoExtension}.py"
to work properly with Qt Designer.
In the automatically compiled ui\_<...>-file the imported module is called <...>\_rc, not rc\_<...>.

**Comment by seanwu1105** [comment]
I haven't used Qt Designer with rcc before. So, could you provide some documentation for my reference or a simple example to help me verify the problem and the corresponding fix?

**Comment by retconx** [comment]
Since I am pretty new to Python and Qt I am not sure if it is an issue concerning Qt Designer or pyside6-uic.
As far as I understand by trying around: if there is a qrc-file in the current folder (e. g. resource.qrc) pyside6-uic generates a line "import resource\_rc" within the compiled ui-file.

**Comment by maflAT** [comment]
I just wanted to mention that the official documentation uses the old prefix naming scheme for ui and rc files:
https://doc.qt.io/qtforpython/tutorials/basictutorial/uifiles.html#option-a-generating-a-python-class
https://doc.qt.io/qtforpython/tutorials/basictutorial/qrcfiles.html#generating-a-python-file

@retconx is correct that the auto-import uses postfix naming scheme.
But on the other hand, the auto-generated Ui class also uses prefix naming, so it's hard to tell what should be the default.
