### ISSUE TITLE
Plugin compatibility issues with Python 3.7

### ISSUE THREAD

**Issue by hrpzcf** [seanwu1105/vscode-qt-for-python#292]
![2023-03-21_172302](https://user-images.githubusercontent.com/58855572/226646960-25ac9316-148c-4459-924f-13102728a08d.png)
![2023-03-21_164359](https://user-images.githubusercontent.com/58855572/226646970-b1a8e648-4d6d-4b44-a52c-8374de0ce411.png)

两个截图中的问题是关于 := 运算符和 typing.Literal 的，据我所知这两个都是 Python 3.8+ 可用。
请问作者是否有意修复这些问题以增加对 Python 3.7 的支持？

**Comment by seanwu1105** [comment]
Thanks for the report. I will remove the use of these language features in the next release.

**Comment by seanwu1105** [comment]
Note that, according to [the official docs](https://devguide.python.org/versions/), Python 3.7 will end its life this June. Thus, we will drop the support at that time and use all language features compatible to 3.8+.

**Comment by ross-g** [comment]
Could I request this be reconsidered @seanwu1105 ?

While Python 3.7 is now end of life, many applications with embedded Python are still on 3.7. So far as I can see the only incompatibility is the use of the "walrus" operator in `scripts/utils/__init__.py` which seems trivial enough that 3.7 support could be maintained without development effort.

**Comment by seanwu1105** [comment]
Hi @ross-g, I see your point. I will add back 3.7 support then.
