### ISSUE TITLE
Extension makes 'Go to Symbol in Workspace' very slow

### ISSUE THREAD

**Issue by patstew** [seanwu1105/vscode-qt-for-python#293]
Having this extension enabled makes VS Code's 'Go to Symbol in Workspace' function very slow, taking 30s or more to show anything at all.

**Comment by patstew** [comment]
Yes, I don't get any results for any languages for a long time, whereas with this extension disabled I get instant results as I type from clangd. Disabling qmlls did nothing.

**Comment by seanwu1105** [comment]
Unfortunately, it cannot be reproduced on my end. Could you try to disable each features in the extension configuration to help me locate the possible cause? Also, please provide the environment and other extensions you installed.

**Comment by seanwu1105** [comment]
Close due to no response.
