### ISSUE TITLE
Error with file name "rc_resource.py"

### ISSUE THREAD

**Issue by verzhbovskyi** [seanwu1105/vscode-qt-for-python#294]
When compiling file "input.qrc" extension sets default name as "rc_file.py", but when compile "file.ui" relative import of .qrc in it sets as:

import file_rc.py

So if I try to launch app, import wont be found. It`s not very big issue, it`s not hard to rename manually, but when many files in project, it`s easy to get lost

Sorry, can`t make pull req, bcs not writing in TypeScript

**Comment by pzhlkj6612** [comment]
\* A tip about Markdown for @verzhbovskyi :

> So if I try to launch app, import wont be found. It`s not very big issue, it`s not hard to rename manually, but when many files in project, it`s easy to get lost

```markdown
So if I try to launch app, import wont be found. It`s not very big issue, it`s not hard to rename manually, but when many files in project, it`s easy to get lost
```

Using backticks (\`) makes wrong rendering; please use single quotes (') instead.
