### ISSUE TITLE
qmml import from pyside_tool fails

### ISSUE THREAD

**Issue by dchelnokov** [seanwu1105/vscode-qt-for-python#297]
Hi, I've just installed the plugin Qt for Python v.7.2.2 and get the error notification as below:
`Traceback (most recent call last): File "c:\Users\UserName\.vscode\extensions\seanwu.vscode-qt-for-python-7.2.2\python\scripts\qmlls.py", line 13, in <module> from PySide6.scripts.pyside_tool import qmlls ImportError: cannot import name 'qmlls' from 'PySide6.scripts.pyside_tool' (C:\Program Files\Python39\lib\site-packages\PySide6\scripts\pyside_tool.py) 
Command failed: "C:\Program Files\Python39\python" c:\Users\UserName\.vscode\extensions\seanwu.vscode-qt-for-python-7.2.2\python\scripts\qmlls.py --help Traceback (most recent call last): 
File "c:\Users\UserName\.vscode\extensions\seanwu.vscode-qt-for-python-7.2.2\python\scripts\qmlls.py", line 13, in <module> from PySide6.scripts.pyside_tool import qmlls ImportError: cannot import name 'qmlls' from 'PySide6.scripts.pyside_tool' (C:\Program Files\Python39\lib\site-packages\PySide6\scripts\pyside_tool.py)`
I am using PySide 6.1.2 for Python 3.9.1 and in my PySide6.scripts.pyside_tool there are only the following functions
- designer()
- genpyi()
- main()
- qt_tool_wrapper(qt_tool, args)
- rcc()
- uic()

Do I have to find and install the "_qmmls.py_"? Thank you.
P.S. My Visual Code has version 1.77.0

**Comment by seanwu1105** [comment]
It requires PySide 6.4 or later to get qmlls. Try to update your dependency to see if the problem still exists.

**Comment by dchelnokov** [comment]
Hi, thank you for support. 
After entering these commands the error notification disappeared:
`python -m pip install --upgrade pip `
and
`python -m pip install --upgrade pyside6`
