### ISSUE TITLE
Proper syntax for pyside2-uic and pyside2-rcc settings entries

### ISSUE THREAD

**Issue by z33kz33k** [seanwu1105/vscode-qt-for-python#3]
The comment for the `pyside2-uic` setting says:

> The path of UI compiler of Qt for Python (PyQt5 or PySide2). For example, `pyuic5 -d -o ./"${fileBasenameNoExtension}.py"` for PyQt5 or `pyside2-uic -d -o ./"${fileBasenameNoExtension}.py"` for PySide2.

but you can't have `""` inside a JSON string and if I just omit them having it like this:
`"qtForPython.path.pyuic": "pyside2-uic -o ${fileBasenameNoExtension}.py"`

it doesn't work (there's a pop-up saying _Trying to open Python UI compiler_ and nothing happens). I have `pyside2-uic.exe` on $PATH. The same applies to the corresponding setting for `pyside2-rcc`.

Escaping the quotes doesn't work either:
`"qtForPython.path.pyuic": "pyside2-uic -o \"${fileBasenameNoExtension}.py\""`

Also it would be nice to have some sort of feedback from the shell to know what's going on.

I'm on Windows 7. More info:

> Version: 1.36.1 (system setup)
> Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
> Date: 2019-07-08T22:59:35.033Z
> Electron: 4.2.5
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 6.1.7601

**Comment by z33kz33k** [comment]
OK. So it the quotes actually don't matter. You can have it like:
`"qtForPython.path.pyuic": "pyside2-uic -o ${fileBasenameNoExtension}.py"`
or
`"qtForPython.path.pyuic": "pyside2-uic -o \"${fileBasenameNoExtension}.py\""`
and it works in both cases.

The thing was I was looking in the directory where the `.ui` file was located and the corresponding `.py` was generated in the workplace's root. So the working solution for me was:
`"qtForPython.path.pyuic": "pyside2-uic -o ${fileDirname}\\${fileBasenameNoExtension}.py"`

Also it's important to remember that for `"${fileBasenameNoExtension}` gets its value from the **currently opened file**.

Closing the issue.

**Comment by seanwu1105** [comment]
When I wrote the comment for the `pyside2-uic` setting, I assume users use the Setting Editor (UI) for configuration. Therefore, users could enter the path directly without escaping `"`.

> Also it would be nice to have some sort of feedback from the shell to know what's going on.

Thanks for the suggestion. I would try to add more feedback (e.g. notification popups) in future versions.
