### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by forallsunday** [seanwu1105/vscode-qt-for-python#305]
ParseError: Invalid qrc file: {"issues":[{"code":"invalid_type","expected":"object","received":"array","path":["RCC","qresource"],"message":"Expected object, received array"}],"name":"ZodError"} ([object Object])

![image](https://user-images.githubusercontent.com/41034184/232647532-2d429028-68e7-4f4f-89c1-3e33789df702.png)

**Comment by seanwu1105** [comment]
Please provide the qrc file for me to reproduce the error.

**Comment by seanwu1105** [comment]
Close as I cannot reproduce the error with the latest version of the extension.
