### ISSUE TITLE
qmlls.exe, you will report an error every time you start

### ISSUE THREAD

**Issue by fggzs** [seanwu1105/vscode-qt-for-python#306]
![1682841720042](https://user-images.githubusercontent.com/66383219/235342545-297b7501-3478-4a51-a017-2dbab720b72a.jpg)

The error message is as follows

**Comment by seanwu1105** [comment]
That's odd. When I was developing the extension, the command did not show this blocking window. Could you provide your environment info, including Windows version, Python version, PySide version?

**Comment by seanwu1105** [comment]
Close due to no response.
