### ISSUE TITLE
No qmlls can be found in current Python environment.

### ISSUE THREAD

**Issue by Damon-Yin** [seanwu1105/vscode-qt-for-python#307]
No qmlls can be found in current Python environment. 
Command failed: C:\Users\lenovo\.vscode\extensions\seanwu.vscode-qt-for-python-7.3.2\python\scripts\qmlls.py --help No qmlls can be found in current Python environment.
![](https://ypxmy.oss-cn-hangzhou.aliyuncs.com/img/202305222224514.jpg)

**Comment by seanwu1105** [comment]
As the message indicates, the extension could not find qmlls. Make sure you have the latest PySide installed or set the path manually.
