### ISSUE TITLE
"No qmlls can be found in current Python environment."

### ISSUE THREAD

**Issue by rokejulianlockhart** [seanwu1105/vscode-qt-for-python#308]
When I invoked [`$HOME/RTBJK9/code/manage_monitors/code/attempts/1 (QML Plasmoid)/manage_monitors-0/ui/main.qml `](https://github.com/seanwu1105/vscode-qt-for-python/files/11565720/main.zip) (cloned from https://gitlab.com/rokejulianlockhart/RTBJK9/-/blob/main/code/manage_monitors/code/attempts/1%20(QML%20Plasmoid)/manage_monitors-0/ui/main.qml) in `code-insiders`,

<blockquote>

No qmlls can be found in current Python environment.

Command failed: /bin/python3.11 /home/rokejulianlockhart/.vscode-insiders/extensions/seanwu.vscode-qt-for-python-7.3.2/python/scripts/qmlls.py --help
No qmlls can be found in current Python environment.

</blockquote>

<details>

![image](https://github.com/seanwu1105/vscode-qt-for-python/assets/42837531/38cec2d2-1d2c-4949-895c-e30eb305d843)

</details>

appeared.

**Comment by seanwu1105** [comment]
This extension is not tested with an insider version. Please use the stable version instead. Also, as the message indicates, the extension could not find qmlls. Make sure you have the latest PySide installed or set the path manually.

**Comment by mkdzhall** [comment]
I'm getting the same issue, I have PyQt5 instead and not PySide for Qt for building a distributable .exe in python.
Where should I set the path manually? 
Not really finding documentation on how to properly set it up in VS Code.
