### ISSUE TITLE
Unable to compile ui file

### ISSUE THREAD

**Issue by 1604042736** [seanwu1105/vscode-qt-for-python#310]
When I click "Compile Qt UI File(uic)", there is no response.

This is my config. 
"pyuic5" is in my environment variable.
![Snipaste_2023-07-27_07-21-37](https://github.com/seanwu1105/vscode-qt-for-python/assets/61647477/1728df93-7eaf-4b8a-9d88-05220243f13d)

**Comment by seanwu1105** [comment]
Please provide your environment and extension output.

**Comment by 1604042736** [comment]
I use windows10 and python 3.11.2.
I can't find the relevant output. "pyuic5" can run in the terminal.

**Comment by seanwu1105** [comment]
The output can be found in the same area as the terminal. The tab is called "Output".

It is likely you do not enable the same Python environment as your terminal so the extension could not locate pyuic5. Do you select the correct Python interpreter?

**Comment by 1604042736** [comment]
I still can't find any relevant output. I'm sure I select the correct Python interpreter. (I use PyQt5)
But after I reinstall, "Qt for Python" appeared in the output and the function can be used normally.
Before this, "Qt for Python" was not included in the output and other functions cannot be used either.

**Comment by seanwu1105** [comment]
Glad the reinstallation solves the problem.
