### ISSUE TITLE
`Preview QML File` can not hot reload when .qml modified

### ISSUE THREAD

**Issue by Honghe** [seanwu1105/vscode-qt-for-python#317]
**Describe the Bug** A clear and concise description of what the bug is.  
`Preview QML File` can not hot reload when the `.qml` modified.

**To Reproduce** Steps to reproduce the behavior:

1. Modify the `.qml` file
2. See error

**Expected Behavior** A clear and concise description of what you expected to happen.  
The `.qml` preivew window will auto reload.

**Screenshots** If applicable, add screenshots to help explain your problem.
The Output:
```
[INFO  - 8:37:38 PM] qmlls is running with the command: 'C:\Users\a\miniconda3\envs\qt65\python.exe c:\Users\a\.vscode\extensions\seanwu.vscode-qt-for-python-7.6.0\python\scripts\qmlls.py'
[Warn  - 8:37:38 PM] registration of file udates failed, will miss file changes done outside the editor due to error -32603 Request client/registerCapability failed with message: No feature implementation for workspace.didChangeWatchedFiles found. Registration failed.
[INFO  - 8:38:28 PM] {
  "stdout": "",
  "command": "C:\\Users\\a\\miniconda3\\envs\\qt65\\python.exe c:\\Users\\a\\.vscode\\extensions\\seanwu.vscode-qt-for-python-7.6.0\\python\\scripts\\qml.py c:\\Users\\a\\Downloads\\demo_unotes\\view.qml"
}
```

**Environment (please complete the following information)**

- OS: Windows 10
- Visual Studio Code version: 1.83
- PySide version: 6.5.3
- Python version: 3.10

**Extension Configurations** Please provide the extension configurations here.  
Default setting.

**Additional context** Add any other context about the problem here.
NA

**Comment by seanwu1105** [comment]
The command is just a wrapper of `pyside6-qml` executable and `pyside6-qml` does not provide any hot-reload feature.
