### ISSUE TITLE
pyside6 support

### ISSUE THREAD

**Issue by j209** [seanwu1105/vscode-qt-for-python#70]
When you implement  [qt for python 6](https://doc.qt.io/qtforpython/index.html) support?

**Comment by seanwu1105** [comment]
@j209 It's been a long time I stop developing in GUI with Python. I might resume working on this extension in the future if I have time. However, I cannot give you any estimated time when I will implement the support for the update,

**Comment by pjx206** [comment]
@j209 The latest version now has support for pyside6.

**Comment by seanwu1105** [comment]
Close with #88.
