### ISSUE TITLE
Support QML Linter

### ISSUE THREAD

**Issue by seanwu1105** [seanwu1105/vscode-qt-for-python#8]
Enable `qmllint` support. ~~Waiting for [QML language server protocol](https://bugreports.qt.io/browse/QTBUG-68406) to be completed.~~

- [ ] ~~Build simple `qmlls` integration~~
  - [ ] ~~Build `qmlls`: [NEEDS MORE INFO/HELP](https://forum.qt.io/topic/137975/how-to-build-qmlls-binary-from-source)~~
  - [ ] ~~Install `aqtinstall` in venv with TypeScript~~
  - [ ] ~~Install corresponding Qt modules/dependencies to the host (minimum deps)~~
  - [ ] ~~Build LS client~~
  - [ ] ~~Apply [LSP inspector](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-log-streaming-sample)~~
  - [ ] ~~Build a practical RESTful PySide6 app with working `qmlls`~~
- [ ] ~~Support [multiple workplace](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-multi-server-sample)~~

**Comment by matheusmb** [comment]
Any update on this?

**Comment by seanwu1105** [comment]
@matheusmb I am still waiting for [this PR](https://codereview.qt-project.org/c/qt/qtdeclarative/+/237614/66) to be merged. Since the LSP is written in C++ but I am not good at the language, I need more time to leverage the tool into this extension. It would be wonderful if you can provide a PR.

**Comment by Aniw777** [comment]
> Enable `qmllint` support. Waiting for [QML language server protocol](https://bugreports.qt.io/browse/QTBUG-68406) to be completed.

I have your Qt for Python VSCode extension humming away for a huge chunk of what I'm working on these days... very nice!
...but once in a while I really wish the **Outline** feature was implemented.

I'm only guessing, but is _QML language server protocol_ a required dependency for the **Outline** to work also?  ( If it was a simple thing I might see about trying to do Outline, but I think the Language Server Protocol world is probably beyond my abilities. )

Regardless, thank you for this quite useful Extension. 😃 👍

**Comment by seanwu1105** [comment]
@Aniw777 I believe the outline functionality should be implemented with (LSP Document Symbol Request)[https://microsoft.github.io//language-server-protocol/specifications/specification-3-14/].
