### ISSUE TITLE
Compile ui

### ISSUE THREAD

**Issue by betopicapiedra** [seanwu1105/vscode-qt-for-python#95]
_**### Hi I have tried to compile the ui file to py using this instruction
pyuic6 -o ./"${fileBasenameNoExtension}.py
but it doesn't work for me (I have PyQt6 installed)**_

**Comment by betopicapiedra** [comment]
This is what I get error

Command failed: pyuic6 -o ./"login.py "c:\Users\Yahve\Documents\Qt python\login.ui" Error: Invalid argument: './login.py c:\Users\Yahve\Documents\Qt'

**Comment by ShayBox** [comment]
To anyone finding this, I had to figure it out, `pyside6-uic -g python -o ${fileDirname}/${fileBasenameNoExtension}_ui.py`, change the command to whatever you're using, the examples in the settings don't work.

**Comment by seanwu1105** [comment]
Closing with 47f6d9ecfc278b8e3897ae4be605bd28d349b89e on v1.0.0.
